server:
  port: 8002
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 114.132.246.22
      port: 6379
      password: PHRmUcd6ZpM0506N1wldC9EKsix77VA8HwMHloLJPZtxSkMnRfEKSn8SYpvcaI5
  application:
    name: short-link-admin
  cloud:
    nacos:
      server-addr: 114.132.246.22:8848
      # 注册
      discovery:
        namespace: short_link
        group: short-link-admin
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #开启mybatis-plus的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #告知映射文件的位置
  mapper-locations: classpath*:/dao/mapper/**/*.xml

logging:
  level:
    com.lyh.shortlink.admin: debug
shortlink:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 30