server:
  port: 8001
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #开启mybatis-plus的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #告知映射文件的位置
  mapper-locations: classpath*:/dao/mapper/**/*.xml

logging:
  level:
    com.lyh.shortlink.project: debug

shortlink:
  domain:
    default: jsuccw.com:8001
  stats:
    locale:
      amap-key: fdc5f3c48b2d743679e12ecc74065ea1
  goto-domain:
    black-list:
      enable: true
      names: '米哈游'
      details:
        - mihoyo.com